AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digitized-av-notifications

  Handles notifications for validation and packaging of incoming digitized audiovisual assets.

Globals:
  Function:
    Timeout: 3

Parameters:
  TeamsUrl:
    Type: String
    Description: The URL of an incoming webhook for a Teams channel to which notifications should be posted.
  AccountId:
    Type: String
    Description: ARN for organization account.
  SnsTopicName:
    Type: String
    Default: digitized-av-events
    Description: Name of SNS topic to trigger Lambda

Resources:
  HandleDigitizedAvNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handle_digitized_av_notifications.lambda_handler
      FunctionName: digitized_av_notifications
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TEAMS_URL:
            Ref: TeamsUrl
      Events:
        DigitizedAvEvents:
          Type: SNS
          Properties:
            Topic: !Sub arn:aws:sns:${AWS::Region}:${AccountId}:${SnsTopicName}

Outputs:
  HelloWorldFunction:
    Description: "Handle Digitized AV Notifications Lambda Function ARN"
    Value: !GetAtt HandleDigitizedAvNotificationsFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HandleDigitizedAvNotificationsFunctionRole.Arn
